---
dxr:
  www_root: '/'
  workers: 4
  default_tree: 'mozilla-central'
  disabled_plugins: ''
  enabled_plugins: '*'
  es_hosts:
    - http://node46.bunker.scl3.mozilla.com:9200/
    - http://node47.bunker.scl3.mozilla.com:9200/
    - http://node48.bunker.scl3.mozilla.com:9200/
    - http://node49.bunker.scl3.mozilla.com:9200/
  es_catalog_replicas: 4
  es_catalog_index: 'dxr_catalog'
  es_index: 'dxr_hot_{format}_{tree}_{unique}'
  es_alias: 'dxr_{format}_{tree}'
  es_indexing_timeout: 60
  es_refresh_interval: 30

defaults:
  disable: false
  schedule: '@weekly'
  quiet_period: 3600
  job_weight: 1
  build_command: ''   # DXR's default is 'make ...'
  mail_rcpts: fubar@mozilla.com
  docker_img: 'klibby/dxr-es'
  docker_vol: '/data/dxr_data:/builds/dxr-build-env/src'
  dxr_plugins:
    - plugin: 'python'
      python_path: '/builds/dxr-build-env/venv/lib64/python2.7'
    - plugin: 'buglink'
      name: 'bugzilla'
      url: 'https://bugzilla.mozilla.org/show_bug.cgi?id=%s'
      regex: '"(?i)bug\s+#?([0-9]+)"'

trees:
  - name: 'mozilla-central'
    url: 'https://hg.mozilla.org/mozilla-central'
    schedule: 'H H/4 * * *'
    quiet_period: 14400
    job_weight: 4
    build_command: 'cd $source_folder && make -f client.mk build MOZ_MAKE_FLAGS="-s -j{workers}"'
    mozconfig:
      - 'mk_add_options AUTOCLOBBER=1'
      - 'ac_add_options --enable-debug'
      - 'ac_add_options --enable-stdcxx-compat'
      - 'ac_add_options --disable-elf-hack'

  - name: 'comm-central'
    url: 'https://hg.mozilla.org/comm-central'
    disable: True
    schedule: 'H H/4 * * *'
    quiet_period: 14400
    job_weight: 4
    build_command: 'cd $source_folder && python client.py checkout && make -f client.mk build MOZ_MAKE_FLAGS="-s -j{workers}"'
    mozconfig:
      - 'mk_add_options AUTOCLOBBER=1'
      - 'ac_add_options --enable-debug'
      - 'ac_add_options --enable-application=suite'
      - 'ac_add_options --disable-optimize'
      - 'ac_add_options --disable-stdcxx-compat'
      - 'ac_add_options --disable-elf-hack'

  - name: 'build-central'
    disable: True
    url: 'https://hg.mozilla.org/build/*'
    job_weight: 2
    build_command: ''

  - name: 'hgcustom:version-control-tools'
    url: 'https://hg.mozilla.org/hgcustom/version-control-tools'

  - name: 'test-hgcustom_version-control-tools'
    url: 'https://hg.mozilla.org/hgcustom/version-control-tools'
    subpath: 'hgcustom/version-control-tools-test'
    docker_img: 'klibby/dxr-es-test'

  - name: 'rust'
    url: 'https://github.com/rust-lang/rust.git'
    docker_img: 'klibby/dxr-es-ubuntu'
    quiet_period: 14400
    job_weight: 4
    build_command: 'cd $source_folder && ./configure --disable-libcpp --enable-clang && make -j{workers}'
    plugins:
      - plugin: 'buglink'
        name: 'github'
        url: 'https://github.com/mozilla/rust/issues/%s'
        regex: '#([0-9]+)'

  - name: 'test-mozilla-central'
    url: 'https://hg.mozilla.org/mozilla-central'
    subpath: 'mozilla-central-test'
    docker_img: 'klibby/dxr-es-test'
    quiet_period: 14400
    job_weight: 4
    build_command: 'cd $source_folder && make -f client.mk build MOZ_MAKE_FLAGS="-s -j{workers}"'
    mozconfig:
      - 'mk_add_options AUTOCLOBBER=1'
      - 'ac_add_options --enable-debug'
      - 'ac_add_options --enable-stdcxx-compat'
      - 'ac_add_options --disable-elf-hack'

