---
- name: install system packages
  yum: pkg={{ item }} state=present
  with_items:
    - curl
    - wget
    - git
    - logrotate
    - python
    - python-devel
    - python-setuptools
    - python-virtualenv

- name: create /data directory
  file: path=/data
        state=directory
        owner=root
        group=root
        mode=0755

- name: create NFS mount point
  file: path=/data/dxr_data
        state=directory
        owner=2352
        group=root
        mode=0755

## https://github.com/ansible/ansible/issues/10941
# Ansible supports NEITHER https_proxy NOR a proxy host entry without http(s)://
# and lots of software obeys the loose proxy spec their own way
## until the above is fixed, manage proxies via puppet
- name: configure DC proxies in /etc/environment
  template: src=environment.j2
            dest=/etc/environment
            owner=root
            group=root
            mode=0644
