---
- name: install system packages
  yum: pkg={{ item }} state=present
  with_items:
    - curl
    - git
    - logrotate
    - mercurial
    - python
    - python-devel
    - python-setuptools
    - python-virtualenv

- name: create /data directory
  file: path=/data
        state=directory
        owner=root
        group=root
        mode=0755

- name: create NFS mount point
  file: path=/data/dxr_data
        state=directory
        owner=5507
        group=root
        mode=0755

## https://github.com/ansible/ansible/issues/10941
# Ansible supports NEITHER https_proxy NOR a proxy host entry without http(s)://
# and lots of software obeys the loose proxy spec their own way
## until the above is fixed, manage proxies via puppet
#- name: configure DC proxies in /etc/environment
#  copy: dest=/etc/environment
#        src=environment
#        owner=root
#        group=root
#        mode=0644
