---
- name: install system packages
  yum: pkg={{ item }} state=present
  with_items:
    - git
    - mercurial
    - python27
    - python27-devel
    - python27-setuptools
    - python27-virtualenv
    - python27-mod_wsgi
    - nodejs
    - npm

- name: create data dirs and NFS mount point
  file: path={{ item }} state=directory owner=root group=root mode=0755
  with_items:
    - /data/prod/builds
    - /data/stage/builds
    - /data/dxr_data

- name: create src symlinks
  file: path=/data/dxr_data dest=/data/{{ item }}/src state=link
  with_items:
    - prod
    - stage

- name: create DXR configs
  copy: src=dxr-{{ item }}.config dest=/data/{{ item }}/dxr.config mode=0644 owner=root group=apache
  with_items:
    - prod
    - stage

# cron jobs to deploy
