---

- name: add epel yum repo
  yum:
    name: "http://download.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present

- name: Import EPEL GPG key.
  rpm_key:
    key: "/etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-{{ ansible_distribution_major_version }}"
    state: present

- name: install system packages
  yum: pkg={{ item }} state=present
  with_items:
    - git
    - logrotate
    - mercurial
    - python27
    - python27-devel
    - python27-setuptools
    - python27-virtualenv
    - python27-mod_wsgi
    - nodejs
    - npm

- name: create data dirs and NFS mount point
  file: path={{ item }} state=directory owner=root group=root mode=0755
  with_items:
    - /data/prod/builds
    - /data/stage/builds
    - /data/dxr_data

- name: create src symlinks
  file: src=/data/dxr_data dest=/data/{{ item }}/src state=link
  with_items:
    - prod
    - stage

- name: fix virtualenv link
  file: src=/usr/bin/virtualenv-2.7 dest=/usr/bin/virtualenv state=link

- name: create DXR configs
  get_url: url=https://github.com/klibby/dxr-docker/raw/{{ item.value.branch }}/dxr.config dest=/data/{{ item.key }}/dxr.config mode=0644 owner=root group=apache force=yes
  with_dict: "{{ environ }}"

- name: add logrotate config
  copy: src=logrotate.conf dest=/etc/logrotate.d/dxr

# TODO enable once Ansible 2.0 is released
# - name: cronvar: user=root name=MAILTO value="..."

- name: create prod deploy cron job
  cron: name="dxr prod deploy"
        minute="*/5"
        job="/data/prod/dxr-prod/virtualenv/bin/dxr deploy -c /data/prod/dxr.config -b /data/prod -k prod 1>>/var/log/dxr-prod.log"

- name: create staging deploy cron job
  cron: name="dxr staging deploy"
        minute="*/5"
        job="/data/stage/dxr-stage/virtualenv/bin/dxr deploy -c /data/stage/dxr.config -b /data/stage -h es -k stage 1>>/var/log/dxr-stage.log"
        state=absent

