---
# cf https://github.com/geerlingguy/ansible-role-jenkins
# or https://github.com/ICTO/ansible-jenkins (for Ubuntu)

- name: create slave directory
  file: path=/data/slaves
        state=directory
        owner=root
        group=root
        mode=0755

- name: add openresty yum repo
  get_url: url="{{ openresty_repo_url }}"
           dest=/etc/yum.repos.d/OpenResty.repo

- name: add openresty key
  rpm_key: key="{{ openresty_repo_key_url }}" state=present

- name: add jenkins yum repo
  get_url: url="{{ jenkins_repo_url }}"
           dest=/etc/yum.repos.d/jenkins.repo

- name: add jenkins key
  rpm_key: key="{{ jenkins_repo_key_url }}" state=present

- name: add epel-release yum repo
  yum:
    name: "http://dl.fedoraproject.org/pub/epel/epel-release-latest-{{ ansible_distribution_major_version }}.noarch.rpm"
    state: present

- name: install packages
  yum: pkg={{ item }} state=present
  with_items:
    - jenkins
    - java-1.8.0-openjdk
    - openresty
    - openssl-devel
    - lua-devel
    - luarocks

- name: install lua-resty-openidc module
  command: luarocks install lua-resty-openidc
  notify: restart openresty

- name: fix openidc module (temp)
  get_url: url="{{ lua_resty_openidc_url }}"
           dest=/usr/share/lua/5.1/resty/
  notify: restart openresty

- name: install openidc_layer shim
  copy: src=openidc_layer.lua
        dest=/usr/local/openresty/nginx/conf/openidc_layer.lua
  notify: restart openresty

- name: install nginx.conf file
  template: src=nginx.conf.j2
            dest=/usr/local/openresty/nginx/conf/nginx.conf
  notify: restart openresty

- name: create conf.d directory
  file: path="/usr/local/openresty/nginx/conf/conf.d"
        state=directory

- name: install vhost config
  template: src=nginx-vhost.conf.j2
            dest="/usr/local/openresty/nginx/conf/conf.d/{{ domain }}.conf"
  notify: restart openresty

- name: install OIDC config loader
  template: src=ldap_pwless.lua.j2
            dest="/usr/local/openresty/nginx/conf/conf.d/ldap_pwless.lua"
  notify: restart openresty

- name: install contribute.json
  template: src=contribute.json.j2
            dest=/var/www/html/contribute.json

- name: add logrotate config
  copy: src=logrotate.conf dest=/etc/logrotate.d/nginx

- name: make nginx vhost logdir
  file: path="/var/log/nginx/{{ domain }}"
        state=directory
        owner=nginx
        group=wheel
        mode=0750

- name: manage openresty service
  service: name=openresty
           enabled=yes
           state=started

- name: make jenkins logdir
  file: path=/var/log/jenkins
        state=directory
        owner=jenkins
        group=jenkins
        mode=0755

- name: change jenkins config
  lineinfile: dest=/etc/sysconfig/jenkins
              regexp="{{ item.regexp }}"
              line="{{ item.line }}"
  with_items:
    - { regexp: '^JENKINS_ARGS=', line: 'JENKINS_ARGS=--prefix=/{{ jenkins_prefix }}' }
  notify: restart jenkins

- name: enable jenkins service
  service: name=jenkins state=started enabled=yes

- name: wait for jenkins to start
  shell: curl --head --silent http://localhost:8080/{{ jenkins_prefix }}/whoAmI/
  register: result
  until: result.stdout.find("200 OK") != -1
  retries: "{{ jenkins_connection_retries }}"
  delay: "{{ jenkins_connection_delay }}"
  changed_when: false

- name: Get the jenkins-cli jarfile from the Jenkins server.
  get_url:
    url: "http://localhost:8080/{{ jenkins_prefix }}/jnlpJars/jenkins-cli.jar"
    dest: "{{ jenkins_jar_location }}"
    force: yes
  register: jarfile_get
  until: "'OK' in jarfile_get.msg or 'file already exists' in jarfile_get.msg"
  retries: 5
  delay: 15

- name: Create /etc/ssh/ssh_known_hosts
  copy: src=ssh_known_hosts
        dest=/etc/ssh/ssh_known_hosts
        owner=root
        group=root
        mode=0644

# Credentials used by plugin install need to be managed some how, but
# secrets in credentials.xml are encrypted with a master secret

# Update Jenkins and install configured plugins.
- include: plugins.yml
