---
# cf https://github.com/geerlingguy/ansible-role-jenkins
# or https://github.com/ICTO/ansible-jenkins (for Ubuntu)

- name: create directories
  file: path={{ item }} state=directory owner=root group=root mode=0755
  with_items:
    - /data

- name: ensure curl is installed
  yum: pkg=curl state=installed

- name: add jenkins yum repo
  get_url: url="{{ jenkins_repo_url }}" dest=/etc/yum.repos.d/jenkins.repo

- name: add jenkins key
  rpm_key: key="{{ jenkins_repo_key_url }}" state=present

- name: install packages
  yum: pkg={{ item }} state=present
  with_items:
    - jenkins
    - java-1.8.0-openjdk

- name: enable jenkins service
  service: name=jenkins state=started enabled=yes

- name: wait for jenkins to start
  shell: curl --head --silent http://{{ jenkins_hostname }}:8080/cli/
  register: result
  until: result.stdout.find("200 OK") != -1
  retries: "{{ jenkins_connection_retries }}"
  delay: "{{ jenkins_connection_delay }}"
  changed_when: false

- name: Get the jenkins-cli jarfile from the Jenkins server.
  get_url:
    url: "http://{{ jenkins_hostname }}:8080/jnlpJars/jenkins-cli.jar"
    dest: "{{ jenkins_jar_location }}"
  register: jarfile_get
  until: "'OK' in jarfile_get.msg or 'file already exists' in jarfile_get.msg"
  retries: 5
  delay: 15

# Credentials used by plugin install need to be managed some how, but
# secrets in credentials.xml are encrypted with a master secret

# Update Jenkins and install configured plugins.
- include: plugins.yml
