---
# Jenkins doesn't allow updates via CLI, though that is required before plugins
# can be installed via CLI. See: https://gist.github.com/rowan-m/1026918
- name: Create Jenkins updates folder.
  file:
    path: /var/lib/jenkins/updates
    owner: jenkins
    group: jenkins
    mode: 0755
    state: directory

- name: Update Jenkins plugin data.
  shell: >
    curl -L https://updates.jenkins-ci.org/update-center.json | sed '1d;$d' > /var/lib/jenkins/updates/default.json
    creates=/var/lib/jenkins/updates/default.json

- name: Permissions for default.json updates info.
  file:
    path: /var/lib/jenkins/updates/default.json
    owner: jenkins
    group: jenkins
    mode: 0755

- name: Find jenkins ssh port number
  shell: "curl --head --silent http://localhost:8080/{{ jenkins_prefix }}/cli/ | awk -F: '/^X-SSH-Endpoint/ {print $3}'"
  register: jenkins_ssh_port
  changed_when: False
  tags:
    - debug

- name: Install Jenkins plugins.
  sudo: no
  command: >
    ssh -l {{ username | mandatory }} -p {{ jenkins_ssh_port.stdout }} localhost install-plugin {{ item }}
    creates=/var/lib/jenkins/plugins/{{ item }}.jpi
  with_items: jenkins_plugins
  notify: restart jenkins

