---
# read groups['dxr-builders'] for list of slaves
#   create slave config file
#   if get-node then upate_node
#   else add_node
# cannot remove nodes, must do manually
- name: Create slave config files
  template: src=jenkins-slave.j2
            dest=/data/slaves/{{ hostvars[item]['inventory_hostname_short'] }}
            owner=root
            group=root
            mode=0600
  with_items: groups['dxr-builders']
  register: slave_configs
  tags: ['add-slaves']

- name: Read jenkins config
  shell: cat /var/lib/jenkins/config.xml
  register: jenkins_config
  changed_when: False
  tags:
    - debug

- name: Login to jenkins with ssh key
  shell: "java -jar {{ jenkins_jar_location }} -s http://localhost:8080/{{jenkins_prefix }} -i {{ jenkins_key }} login"
  when: '"HudsonPrivateSecurityRealm" in jenkins_config.stdout'

- name: Create temporary password file
  copy:
    dest="{{ user_pw_file }}"
    content="{{ password }}"
    mode=0600
  when: '"LDAPSecurityRealm" in jenkins_config.stdout'

- name: Login to jenkins with LDAP
  shell: "java -jar {{ jenkins_jar_location }} -s http://localhost:8080/{{jenkins_prefix }} -noKeyAuth login --username {{ username | mandatory }} --password-file {{ user_pw_file }}"
  when: '"LDAPSecurityRealm" in jenkins_config.stdout'

- name: Remove temporary password file
  file:
    path="{{ user_pw_file }}"
    state=absent

- name: Verify slave nodes
  shell: "java -jar {{ jenkins_jar_location }} -s http://localhost:8080/{{jenkins_prefix }} get-node {{ hostvars[item.item]['inventory_hostname_short'] }} >> /dev/null"
  when: slave_configs.changed
  with_items: slave_configs.results
  register: get_node
  ignore_errors: True
  tags: ['add-slaves']

- name: Update missing slave nodes
  shell: "java -jar {{ jenkins_jar_location }} -s http://localhost:8080/{{jenkins_prefix }} update-node {{ hostvars[item.item.item]['inventory_hostname_short'] }} < /data/slaves/{{ hostvars[item.item.item]['inventory_hostname_short'] }}"
  when: item.changed and not item.rc != 0
  with_items: get_node.results
  tags: ['add-slaves']

- name: Create missing slave nodes
  shell: "java -jar {{ jenkins_jar_location }} -s http://localhost:8080/{{jenkins_prefix }} create-node {{ hostvars[item.item.item]['inventory_hostname_short'] }} < /data/slaves/{{ hostvars[item.item.item]['inventory_hostname_short'] }}"
  when: item.changed and (item.stderr.find('No such node') != -1)
  with_items: get_node.results
  tags: ['add-slaves']

- name: Logout of jenkins
  shell: "java -jar {{ jenkins_jar_location }} -s http://localhost:8080/{{jenkins_prefix }} logout"
