---
es_user: elasticsearch
es_log_dir: /var/log/elasticsearch
es_lib_dir: /var/lib/elasticsearch
es_run_dir: /var/run/elasticsearch
es_conf_dir: /etc/elasticsearch
es_template_dir: /etc/elasticsearch/templates
es_tmp_dir: /tmp/elasticsearch
es_max_mem: "{{ (ansible_memory_mb.real.total / 1.5)|round|int }}"
nofile_limit: 65535
