---
- name: install system packages
  yum: pkg={{ item }} state=present
  with_items:
    - python27-mod_wsgi
    - httpd
    - mod_auth_mellon

- name: install httpd.conf file
  template: src=httpd.conf.j2 dest=/etc/httpd/conf/httpd.conf
  notify: reload apache

- name: install dxr vhost config
  template: src=vhost.conf.j2 dest=/etc/httpd/conf.d/dxr-vhost.conf
  notify: reload apache

# Infrasec has requested that all of our servers have this
- name: install hostname.conf
  copy: content="Header always set X-Backend-Server {{ ansible_fqdn }}" dest=/etc/httpd/conf.d/hostname.conf

- name: install contribute.json
  copy: src=contribute.json
        dest=/var/www/html/contribute.json

- name: create mellon directory
  file: path=/etc/httpd/mellon state=directory owner=root group=apache mode=0750

- name: make logdir
  file: path=/var/log/httpd/{{ domain }} state=directory owner=apache group=vpn_dxr mode=0755

- name: add logrotate config
  copy: src=logrotate.conf dest=/etc/logrotate.d/httpd

- name: add deploy directories
  file: path={{ item }} state=directory
  with_items:
    - /data/prod
    - /data/stage

- name: manage httpd service
  service: name=httpd enabled=yes state=started

- name: fix virtualenv link
  file: src=/usr/bin/virtualenv-2.7 dest=/usr/bin/virtualenv state=link

- name: manage hgrc
  copy: src=hgrc dest=/etc/mercurial/hgrc

