---
- hosts: dxradm.private.scl3.mozilla.com
  roles:
    - admin
    - jenkins-master

- hosts: dxr-processor1.private.scl3.mozilla.com
  roles:
    - indexer

- hosts: dxr1.stage.webapp.scl3.mozilla.com
  vars:
    domain: dxr.allizom.org
    sitehome: /data/stage
    approot: /data/stage/dxr-staging
  roles:
    - web

- hosts: dxrweb-prod
  vars:
    domain: dxr.mozilla.org
    sitehome: /data/prod
    approot: /data/prod/dxr-prod
  roles:
    - web

