---
- hosts: dxradm.private.scl3.mozilla.com
  vars:
    # need to handle secrets, currently managed by hand. boo.
    jenkins_key: /root/.ssh/jenkins_rsa
    environ:
      prod:
        branch: master
      stage:
        branch: master
  roles:
    - admin
    - jenkins-master

- hosts: dxr-builders
  vars:
    jenkins_master: dxradm.private.scl3.mozilla.com:8080
  roles:
    - indexer
    - jenkins-slave

- hosts: dxr1.stage.webapp.scl3.mozilla.com
  vars:
    domain: dxr.allizom.org
    sitehome: /data/stage
    approot: /data/stage/dxr-stage
  roles:
    - web

- hosts: dxrweb-prod
  vars:
    domain: dxr.mozilla.org
    sitehome: /data/prod
    approot: /data/prod/dxr-prod
  roles:
    - web

