---
- hosts: dxr-jenkins1.dmz.scl3.mozilla.com
  gather_facts: no
  vars_prompt:
    - name: "username"
      prompt: "what is your MoCo email address?"
      private: no

  tasks:
    - name: Find jenkins ssh port number
      sudo: no
      shell: "curl --head --silent http://localhost:8080/{{ jenkins_prefix }}/cli/ | awk -F: '/^X-SSH-Endpoint/ {print $3}'"
      register: jenkins_ssh_port
      changed_when: False

    - name: List jenkins jobs
      sudo: no
      shell: "ssh -l {{ username | mandatory }} -p {{ jenkins_ssh_port.stdout }} localhost list-jobs"
      register: job_list
      when: job_provided is undefined

    - name: Trigger build
      sudo: no
      shell: "ssh -l {{ username | mandatory }} -p {{ jenkins_ssh_port.stdout }} localhost build {{ job_provided }}"
      when: job_provided is defined

    # Hack: if job_list isn't set, supply an empty default to skip the task
    - name: Trigger all jobs
      sudo: no
      shell: "ssh -l {{ username | mandatory }} -p {{ jenkins_ssh_port.stdout }} localhost build {{ item }}"
      with_items: "{{ job_list.stdout_lines | default([])}}"
