---
- name: install packages
  yum: pkg={{item}} state=installed
  with_items:
    - git
    - mercurial
    - lxc
    - lxc-libs
    - docker-io
    - python-setuptools

- name: copy requirements.txt
  copy: src=requirements.txt dest=/data/requirements.txt mode=0644 owner=root group=root

# TODO: we should really use a local copy of peep
# mozilla pip rpm is broken
- name: install pip
  easy_install: name=pip

- name: install requirements
  pip: requirements=/data/requirements.txt

- name: install mercurial bundleclone extension
  get_url: url={{ bundleclone_url }} dest=/data/bundleclone.py mode=0644 force=yes

- name: configure mercurial
  copy: src=hgrc dest=/etc/mercurial/hgrc mode=0664 owner=root group=root

- name: configure docker options
  lineinfile: dest=/etc/sysconfig/docker regexp="^other_args=" line='other_args="--dns=10.22.75.40 --dns=10.22.75.41 --host=tcp://0.0.0.0:6666 --host=unix:///var/run/docker.sock"'
  notify: restart docker

- name: configure docker storage options
  copy: src=docker-storage dest=/etc/sysconfig/docker-storage mode=0644 owner=root group=root
  notify: restart docker

- name: ensure docker is running
  service: name=docker state=started enabled=yes

- name: ensure data directory exists
  file: path=/data/dxr_data owner=jenkins group=root state=directory mode=0755

