---
- name: install packages
  yum: pkg={{item}} state=installed
  with_items:
    - docker
    - java-1.8.0-openjdk
    - python2-pip

- name: update jenkins user groups
  user: name=jenkins
        groups="vpn_dxr,dockerroot"
        append=yes

- name: add authorized_keys for jenkins user
  authorized_key: user=jenkins
                  key_options='from="10.48.74.150"'
                  key="ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA4H+yA2xlG0uCqmFOf5KKoEK/W82o6AbhnVixD4LI5Yi/vDi6TjXcZqgMFIQ5JAGiWrPnan2W6SqVapm8Iv1Zzvezr+8s0y3WoKDCKQSM+g3vuwrAZODt8xpOXn3bluHxNdBTwH97itzoHhyhw2C1gEbpxUMKt5Y/2mSU54WhmleXoTl9GtdJTdEQ+76p2b6E6GODIFrRhXBCcnEy3fwSimHxgKAoU6YqrSThqaFYdjIFJr62frQfwPkVN/bGu683lkZIR7x7cMsU11GR8WRHA1oOKpP4zMyhkuEXxI6VTGOu87kC9xKbjTxkbJOk9ZYmXOPOOCtMdDZE9X5o1jNVTQ=="

#- name: Prevent puppet firewall NAT purging
#  copy: dest=/etc/facter/facts.d/local_firewall_purge_disable.yaml
#        src=local_firewall_purge_disable.yaml
#        owner=root
#        group=root
#        mode=0644

- name: copy requirements.txt
  copy: dest=/data/requirements.txt
        src=requirements.txt
        owner=root
        group=root
        mode=0644

- name: install requirements
  pip: requirements=/data/requirements.txt
  extra_args: "--proxy http://proxy.dmz.mdc1.mozilla.com/"

- name: configure mercurial
  copy: dest=/etc/mercurial/hgrc
        src=hgrc
        owner=root
        group=root
        mode=0664

- name: configure docker options
  lineinfile: dest=/etc/sysconfig/docker
              regexp="^other_args="
              line='other_args="--dns=10.22.75.40 --dns=10.22.75.41 --host=tcp://0.0.0.0:6666 --host=unix:///var/run/docker.sock"'
  notify: restart docker

- name: configure docker storage options
  copy: dest=/etc/sysconfig/docker-storage
        src=docker-storage
        owner=root
        group=root
        mode=0644
  notify: restart docker

- name: ensure docker is running
  service: name=docker
           state=started
           enabled=yes

- name: ensure jenkins directory exists
  file: path={{ jenkins_dir }}
        state=directory
        owner=jenkins
        group=root
        mode=0755

- name: download jenkins slave.jar
  get_url: url="https://{{ jenkins_master }}/{{ jenkins_url_prefix }}/jnlpJars/slave.jar"
           dest={{ jenkins_dir }}/slave.jar
           force=yes
