---
- name: install packages
  yum: pkg={{item}} state=installed
  with_items:
    - docker
    - java-1.8.0-openjdk
    - python2-pip

- name: create docker group
  group: name=docker state=present

- name: update jenkins user groups
  user: name=jenkins
        groups="vpn_dxr,docker"
        append=yes

- name: add authorized_keys for jenkins user
  authorized_key: user=jenkins
                  path=/home/jenkins/.ssh/authorized_keys2
                  key_options='from="10.48.74.150"'
                  key="ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDfs4cOcfb5s+3qn65bYI3V3t9LZfmHADYLlyqe1oP84uJg1JZriJ9JWgjwws0lAXMBFr9rffpMaiMy/8IXnMp495p5N707AOkrZ8UQklvK/oZdgN/YlcKrW+S74NaYzl1tofQjxYgwxYazPS0rfjts/XpOrt438uJIkw5NI0CqkEwawJOm49jCYRT1XFBNKAzstCraHQKrkP9dleL7N87DYuk8Ec5YDyjzfmGX2RSpxp3a1a8nl/to+Tg3FNaMsu4lZLJmF/HGzEfYXhMM0YP59BnUpDadeG0ZwvSbABVakTGOtVm0u1OuZWIlxw++1IuO3EYDpbYV4MPDDZHio87R"

#- name: Prevent puppet firewall NAT purging
#  copy: dest=/etc/facter/facts.d/local_firewall_purge_disable.yaml
#        src=local_firewall_purge_disable.yaml
#        owner=root
#        group=root
#        mode=0644

- name: copy requirements.txt
  copy: dest=/data/requirements.txt
        src=requirements.txt
        owner=root
        group=root
        mode=0644

- name: install requirements
  pip: requirements=/data/requirements.txt
    extra_args="--proxy http://proxy.dmz.mdc1.mozilla.com/"

- name: configure mercurial
  copy: dest=/etc/mercurial/hgrc
        src=hgrc
        owner=root
        group=root
        mode=0644

- name: replace docker.service systemd config
  copy: dest=/usr/lib/systemd/system/docker.service
        src=docker.service
        owner=root
        group=root
        mode=0644
  notify: restart docker

- name: configure docker options
  lineinfile: dest=/etc/sysconfig/docker
              regexp="^other_args="
              line='other_args="--host=tcp://0.0.0.0:6666 --host=unix:///var/run/docker.sock"'
  notify: restart docker

- name: add docker interface to dnsmasq
  copy: dest=/etc/NetworkManager/dnsmasq.d/docker-bridge.conf
        content="interface=docker0"

- name: configure docker dns
  lineinfile: dest=/etc/sysconfig/docker-network
              regexp="^DOCKER_NETWORK_OPTIONS="
              line='DOCKER_NETWORK_OPTIONS="--dns=172.17.0.1"'
  notify: restart docker

- name: ensure docker is running
  service: name=docker
           state=started
           enabled=yes

- name: ensure jenkins directory exists
  file: path={{ jenkins_dir }}
        state=directory
        owner=jenkins
        group=root
        mode=0755

- name: download jenkins slave.jar
  get_url: url="http://{{ jenkins_master }}/{{ jenkins_url_prefix }}/jnlpJars/slave.jar"
           dest={{ jenkins_dir }}/slave.jar
           force=yes
