---
server_limit: "{{ ansible_processor_cores * 10 }}"
max_clients: "{{ ansible_processor_cores * 10 }}"
nginx_repo_url: https://nginx.org/packages/rhel/6/noarch/RPMS/nginx-release-rhel-6-0.el6.ngx.noarch.rpm
jenkins_repo_url: https://pkg.jenkins.io/redhat/jenkins.repo
jenkins_repo_key_url: https://pkg.jenkins.io/redhat/jenkins-ci.org.key
jenkins_connection_delay: 5
jenkins_connection_retries: 60
jenkins_prefix: ""
jenkins_jar_location: /data/jenkins-cli.jar
jenkins_plugins:
  - audit-trail
  - envinject
  - git
  - heavy-job
  - ldap
  - mercurial
  - multiple-scms
  - thinBackup
  - timestamper
