---
server_limit: "{{ ansible_processor_cores * 10 }}"
max_clients: "{{ ansible_processor_cores * 10 }}"
jenkins_repo_url: http://pkg.jenkins-ci.org/redhat/jenkins.repo
jenkins_repo_key_url: http://pkg.jenkins-ci.org/redhat/jenkins-ci.org.key
jenkins_connection_delay: 5
jenkins_connection_retries: 60
jenkins_prefix: jenkins
jenkins_jar_location: /data/jenkins-cli.jar
jenkins_plugins:
  - docker-build-step
  - git
  - mercurial
  - timestamper
  - heavy-job
  - envinject
