---
- name: restart jenkins
  service: name=jenkins state=restarted

- name: restart nginx
  debug: msg="checking config first"
  changed_when: True
  notify:
    - check nginx configuration
    - restart nginx - after config check

- name: check nginx configuration
  shell: "nginx -t"
  register: result
  changed_when: "result.rc != 0"
  always_run: yes

- name: restart nginx - after config check
  service: name=nginx state=restarted
