---
- name: make logdir
  file: path=/var/log/httpd/{{ domain }} state=directory owner=apache group=vpn_dxr mode=0755

- name: install alt vhost config
  template: src=vhost.conf.j2 dest=/etc/httpd/conf.d/mxr-vhost.conf
  notify: reload apache
